// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt18OtckAM6XCkMPPBS4EjNG7_96A1XTg',
    appId: '1:1053083894469:web:2908381b6ef8d3d96926ac',
    messagingSenderId: '1053083894469',
    projectId: 'evently-25425',
    authDomain: 'evently-25425.firebaseapp.com',
    storageBucket: 'evently-25425.firebasestorage.app',
    measurementId: 'G-50L840SE47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_zzJimXizI0u4YUb6ikeM0AgZAWV2eA4',
    appId: '1:1053083894469:android:46e3f4184936d4b06926ac',
    messagingSenderId: '1053083894469',
    projectId: 'evently-25425',
    storageBucket: 'evently-25425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpBwjlp4ayZUeAAvvGfyaF8rDV1dny-5g',
    appId: '1:1053083894469:ios:adad4b633bcda5e86926ac',
    messagingSenderId: '1053083894469',
    projectId: 'evently-25425',
    storageBucket: 'evently-25425.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpBwjlp4ayZUeAAvvGfyaF8rDV1dny-5g',
    appId: '1:1053083894469:ios:adad4b633bcda5e86926ac',
    messagingSenderId: '1053083894469',
    projectId: 'evently-25425',
    storageBucket: 'evently-25425.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt18OtckAM6XCkMPPBS4EjNG7_96A1XTg',
    appId: '1:1053083894469:web:be5fb9b9586dba0b6926ac',
    messagingSenderId: '1053083894469',
    projectId: 'evently-25425',
    authDomain: 'evently-25425.firebaseapp.com',
    storageBucket: 'evently-25425.firebasestorage.app',
    measurementId: 'G-ZN45GY3GHH',
  );
}
